# Generated by Django 4.0 on 2021-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoInicial', models.CharField(max_length=50)),
                ('EstadoFinal', models.CharField(max_length=50)),
                ('Transicoes', models.CharField(max_length=50)),
                ('Estados', models.CharField(max_length=50)),
                ('Alfabeto', models.CharField(max_length=50)),
                ('Descricao', models.CharField(max_length=50)),
            ],
        ),
    ]
