# Generated by Django 4.0 on 2021-12-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTuring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EstadoInicial', models.CharField(default='A', max_length=10000)),
                ('EstadoFinal', models.CharField(default='A', max_length=10000)),
                ('Transicoes', models.CharField(default='A', max_length=10000)),
                ('Estados', models.CharField(default='A', max_length=10000)),
                ('Alfabeto', models.CharField(default='A', max_length=10000)),
                ('Descricao', models.CharField(default='A', max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='automato',
            name='Alfabeto',
            field=models.CharField(default='A', max_length=10000),
        ),
        migrations.AlterField(
            model_name='automato',
            name='Descricao',
            field=models.CharField(default='A', max_length=10000),
        ),
        migrations.AlterField(
            model_name='automato',
            name='EstadoFinal',
            field=models.CharField(default='A', max_length=10000),
        ),
        migrations.AlterField(
            model_name='automato',
            name='EstadoInicial',
            field=models.CharField(default='A', max_length=10000),
        ),
        migrations.AlterField(
            model_name='automato',
            name='Estados',
            field=models.CharField(default='A', max_length=10000),
        ),
        migrations.AlterField(
            model_name='automato',
            name='Transicoes',
            field=models.CharField(default='A', max_length=10000),
        ),
    ]
